<?php

use Phinx\Migration\AbstractMigration;

class CreateInitialTables extends AbstractMigration
{
    public function change()
    {
        // Users table
        $this->table('users', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('email', 'string', ['limit' => 255])
            ->addColumn('full_name', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('password', 'string', ['limit' => 255])
            ->addColumn('role', 'string', ['limit' => 20, 'default' => 'user'])
            ->addColumn('membership_tier', 'string', ['limit' => 20, 'default' => 'free'])
            ->addColumn('membership_expires_at', 'timestamp', ['null' => true])
            ->addColumn('is_active', 'boolean', ['default' => true])
            ->addColumn('is_staff', 'boolean', ['default' => false])
            ->addColumn('is_verified', 'boolean', ['default' => false])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addColumn('last_login_at', 'timestamp', ['null' => true])
            ->addIndex(['email'], ['unique' => true])
            ->addIndex(['role'])
            ->addIndex(['membership_tier', 'membership_expires_at'])
            ->create();

        // User activities table
        $this->table('user_activities', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('user_id', 'biginteger')
            ->addColumn('action', 'string', ['limit' => 100])
            ->addColumn('description', 'text', ['null' => true])
            ->addColumn('ip_address', 'string', ['limit' => 45, 'null' => true])
            ->addColumn('user_agent', 'text', ['null' => true])
            ->addColumn('metadata', 'json', ['null' => true])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['user_id', 'created_at'])
            ->addIndex(['action'])
            ->addForeignKey('user_id', 'users', 'id', ['delete' => 'CASCADE'])
            ->create();

        // Leagues table
        $this->table('leagues', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('api_id', 'integer')
            ->addColumn('name', 'string', ['limit' => 255])
            ->addColumn('country', 'string', ['limit' => 100])
            ->addColumn('logo', 'string', ['limit' => 500, 'null' => true])
            ->addColumn('season', 'integer')
            ->addColumn('is_active', 'boolean', ['default' => true])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['api_id'], ['unique' => true])
            ->addIndex(['country', 'is_active'])
            ->create();

        // Teams table
        $this->table('teams', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('api_id', 'integer')
            ->addColumn('external_id', 'integer', ['null' => true])
            ->addColumn('name', 'string', ['limit' => 255])
            ->addColumn('short_name', 'string', ['limit' => 100, 'null' => true])
            ->addColumn('tla', 'string', ['limit' => 3, 'null' => true])
            ->addColumn('logo', 'string', ['limit' => 500, 'null' => true])
            ->addColumn('crest_url', 'string', ['limit' => 500, 'null' => true])
            ->addColumn('country', 'string', ['limit' => 100, 'null' => true])
            ->addColumn('founded', 'integer', ['null' => true])
            ->addColumn('venue_name', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('position', 'integer', ['null' => true])
            ->addColumn('played_games', 'integer', ['default' => 0])
            ->addColumn('won', 'integer', ['default' => 0])
            ->addColumn('draw', 'integer', ['default' => 0])
            ->addColumn('lost', 'integer', ['default' => 0])
            ->addColumn('points', 'integer', ['default' => 0])
            ->addColumn('goals_for', 'integer', ['default' => 0])
            ->addColumn('goals_against', 'integer', ['default' => 0])
            ->addColumn('goal_difference', 'integer', ['default' => 0])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['api_id'], ['unique' => true])
            ->addIndex(['external_id'])
            ->addIndex(['name'])
            ->addIndex(['position'])
            ->create();

        // Matches table
        $this->table('matches', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('api_id', 'integer', ['null' => true])
            ->addColumn('external_id', 'integer', ['null' => true])
            ->addColumn('league_id', 'biginteger', ['null' => true])
            ->addColumn('home_team_id', 'biginteger')
            ->addColumn('away_team_id', 'biginteger')
            ->addColumn('match_date', 'timestamp')
            ->addColumn('status', 'string', ['limit' => 20, 'default' => 'scheduled'])
            ->addColumn('round', 'string', ['limit' => 100, 'null' => true])
            ->addColumn('competition', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('competition_code', 'string', ['limit' => 10, 'null' => true])
            ->addColumn('matchday', 'integer', ['null' => true])
            ->addColumn('stage', 'string', ['limit' => 50, 'default' => 'REGULAR_SEASON'])
            ->addColumn('home_score', 'integer', ['null' => true])
            ->addColumn('away_score', 'integer', ['null' => true])
            ->addColumn('home_halftime_score', 'integer', ['null' => true])
            ->addColumn('away_halftime_score', 'integer', ['null' => true])
            ->addColumn('statistics', 'json', ['null' => true])
            ->addColumn('events', 'json', ['null' => true])
            ->addColumn('home_odds', 'decimal', ['precision' => 6, 'scale' => 2, 'null' => true])
            ->addColumn('draw_odds', 'decimal', ['precision' => 6, 'scale' => 2, 'null' => true])
            ->addColumn('away_odds', 'decimal', ['precision' => 6, 'scale' => 2, 'null' => true])
            ->addColumn('is_featured', 'boolean', ['default' => false])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['api_id'], ['unique' => true])
            ->addIndex(['external_id'], ['unique' => true])
            ->addIndex(['match_date', 'status'])
            ->addIndex(['league_id', 'match_date'])
            ->addIndex(['status', 'is_featured'])
            ->addForeignKey('league_id', 'leagues', 'id', ['delete' => 'SET_NULL'])
            ->addForeignKey('home_team_id', 'teams', 'id', ['delete' => 'CASCADE'])
            ->addForeignKey('away_team_id', 'teams', 'id', ['delete' => 'CASCADE'])
            ->create();

        // Team statistics table
        $this->table('team_statistics', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('team_id', 'biginteger')
            ->addColumn('league_id', 'biginteger')
            ->addColumn('season', 'integer')
            ->addColumn('matches_played', 'integer', ['default' => 0])
            ->addColumn('wins', 'integer', ['default' => 0])
            ->addColumn('draws', 'integer', ['default' => 0])
            ->addColumn('losses', 'integer', ['default' => 0])
            ->addColumn('goals_for', 'integer', ['default' => 0])
            ->addColumn('goals_against', 'integer', ['default' => 0])
            ->addColumn('form', 'string', ['limit' => 5, 'null' => true])
            ->addColumn('form_score', 'integer', ['default' => 0])
            ->addColumn('home_wins', 'integer', ['default' => 0])
            ->addColumn('home_draws', 'integer', ['default' => 0])
            ->addColumn('home_losses', 'integer', ['default' => 0])
            ->addColumn('away_wins', 'integer', ['default' => 0])
            ->addColumn('away_draws', 'integer', ['default' => 0])
            ->addColumn('away_losses', 'integer', ['default' => 0])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['team_id', 'league_id', 'season'], ['unique' => true])
            ->addIndex(['team_id', 'season'])
            ->addIndex(['league_id', 'season'])
            ->addForeignKey('team_id', 'teams', 'id', ['delete' => 'CASCADE'])
            ->addForeignKey('league_id', 'leagues', 'id', ['delete' => 'CASCADE'])
            ->create();

        // Predictions table
        $this->table('predictions', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('match_id', 'biginteger')
            ->addColumn('prediction_type', 'string', ['limit' => 20])
            ->addColumn('predicted_result', 'string', ['limit' => 10])
            ->addColumn('confidence_score', 'decimal', ['precision' => 5, 'scale' => 2])
            ->addColumn('model_version', 'string', ['limit' => 50, 'default' => 'v1.0'])
            ->addColumn('features_used', 'json')
            ->addColumn('recommended_odds', 'decimal', ['precision' => 6, 'scale' => 2, 'null' => true])
            ->addColumn('actual_odds', 'decimal', ['precision' => 6, 'scale' => 2, 'null' => true])
            ->addColumn('status', 'string', ['limit' => 20, 'default' => 'pending'])
            ->addColumn('actual_result', 'string', ['limit' => 10, 'null' => true])
            ->addColumn('is_premium', 'boolean', ['default' => false])
            ->addColumn('is_featured', 'boolean', ['default' => false])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['match_id', 'prediction_type'])
            ->addIndex(['confidence_score', 'created_at'])
            ->addIndex(['status', 'is_premium'])
            ->addIndex(['created_at'])
            ->addForeignKey('match_id', 'matches', 'id', ['delete' => 'CASCADE'])
            ->create();

        // Coupons table
        $this->table('coupons', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'uuid')
            ->addColumn('user_id', 'biginteger')
            ->addColumn('name', 'string', ['limit' => 255, 'null' => true])
            ->addColumn('coupon_type', 'string', ['limit' => 20, 'default' => 'multiple'])
            ->addColumn('system_min_wins', 'integer', ['null' => true])
            ->addColumn('system_total_picks', 'integer', ['null' => true])
            ->addColumn('stake', 'decimal', ['precision' => 10, 'scale' => 2, 'default' => 0])
            ->addColumn('total_odds', 'decimal', ['precision' => 12, 'scale' => 2, 'default' => 1.00])
            ->addColumn('potential_win', 'decimal', ['precision' => 12, 'scale' => 2, 'default' => 0])
            ->addColumn('status', 'string', ['limit' => 20, 'default' => 'pending'])
            ->addColumn('actual_win', 'decimal', ['precision' => 12, 'scale' => 2, 'default' => 0])
            ->addColumn('profit_loss', 'decimal', ['precision' => 12, 'scale' => 2, 'default' => 0])
            ->addColumn('is_shared', 'boolean', ['default' => false])
            ->addColumn('share_code', 'string', ['limit' => 10, 'null' => true])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['user_id', 'created_at'])
            ->addIndex(['status'])
            ->addIndex(['share_code'], ['unique' => true])
            ->addIndex(['created_at'])
            ->addForeignKey('user_id', 'users', 'id', ['delete' => 'CASCADE'])
            ->create();

        // Coupon picks table
        $this->table('coupon_picks', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('coupon_id', 'uuid')
            ->addColumn('prediction_id', 'biginteger')
            ->addColumn('odds', 'decimal', ['precision' => 6, 'scale' => 2])
            ->addColumn('is_banker', 'boolean', ['default' => false])
            ->addColumn('status', 'string', ['limit' => 20, 'default' => 'pending'])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['coupon_id', 'prediction_id'], ['unique' => true])
            ->addForeignKey('coupon_id', 'coupons', 'id', ['delete' => 'CASCADE'])
            ->addForeignKey('prediction_id', 'predictions', 'id', ['delete' => 'CASCADE'])
            ->create();

        // Formulas table
        $this->table('formulas', ['id' => false, 'primary_key' => ['id']])
            ->addColumn('id', 'biginteger', ['identity' => true])
            ->addColumn('user_id', 'biginteger')
            ->addColumn('name', 'string', ['limit' => 255])
            ->addColumn('description', 'text', ['null' => true])
            ->addColumn('rules', 'json')
            ->addColumn('filters', 'json')
            ->addColumn('is_active', 'boolean', ['default' => true])
            ->addColumn('is_public', 'boolean', ['default' => false])
            ->addColumn('success_count', 'integer', ['default' => 0])
            ->addColumn('fail_count', 'integer', ['default' => 0])
            ->addColumn('success_rate', 'decimal', ['precision' => 5, 'scale' => 2, 'default' => 0])
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->addColumn('updated_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP', 'update' => 'CURRENT_TIMESTAMP'])
            ->addIndex(['user_id', 'created_at'])
            ->addIndex(['is_public', 'success_rate'])
            ->addForeignKey('user_id', 'users', 'id', ['delete' => 'CASCADE'])
            ->create();
    }
}
